package changchun;

import java.io.IOException;
import java.util.LinkedList;
import java.util.List;

import changchun.util.CCutil;
import changchun.util.ClustalOmega;



public class GenomeEdit {
	
	String genomeSeq;
	String templateSeq;
	
	String alignedGenome;
	String alignedTemplate;
	
	int from;
	int to;
	
	public static class FirstLast {
		int indexLeft=0;
		int indexRight=0;
		
		public FirstLast(String s) {
			while(s.charAt(indexLeft)=='-') {
				indexLeft++;
			}
			for(int i=0;i<s.length();i++) {
				if(s.charAt(i)!='-')
					indexRight=i;
			}
		}
		
		public int len() {
			return indexRight-indexLeft;
		}
		
	}
	
	
	public GenomeEdit(String genomeSeq, String templateSeq) throws IOException {
		
		this.genomeSeq = genomeSeq;
		this.templateSeq = templateSeq;
		
		List<String> list1=new LinkedList<>();
		list1.add(genomeSeq);
		list1.add(templateSeq);

		List<String> list2=new LinkedList<>();
		list2.add(genomeSeq);
		list2.add(CCutil.revcomp(templateSeq));

		List<String> res1=ExtractSeqFromMSA.readAlignment(ClustalOmega.call(list1));
		List<String> res2=ExtractSeqFromMSA.readAlignment(ClustalOmega.call(list2));
		
		FirstLast int1=new FirstLast(res1.get(1));
		FirstLast int2=new FirstLast(res2.get(1));
		
		
		/*
		System.out.println(int1.len());
		System.out.println(int2.len());*/
		
		//System.out.println(res1.get(1));
		
		if(int1.len()<int2.len()) {
			alignedGenome=res1.get(0);
			alignedTemplate=res1.get(1);			
			from=int1.indexLeft;
			to=res1.get(0).substring(0,int1.indexRight).replaceAll("-", "").length();
		} else {
			alignedGenome=res2.get(0);
			alignedTemplate=res2.get(1);			
			from=int2.indexLeft;
			to=res2.get(0).substring(0,int2.indexRight).replaceAll("-", "").length();
		}

		/*
		System.out.println();
		System.out.println(from);
		System.out.println(to);*/
	}





	public static void main(String[] args) throws IOException {
		new GenomeEdit(
				"CTGNNNNNNNNCTTAAAGTTTATTCATATTCTTTGAAAACCATCTTATCGGCTCTTCCACAACTCTGTTTAATGTTCCCCGTTAATTCTGCCCGCCAGGCTCAAAACCATGTAGTTGTATTCTTACCAATTTATATGACTTCTGAAGTTTTACCCATCCATTTTCTTTCAAATATATTAAATCTTATGTGTTTTGTTGCTCTCTTTCAATAAATTACGCATCCAAACAAACCGTCGGAACAAAAGACACTTGTGCAAAAATAGTTCAGTATTCCTGCAACACTAAAACTAAACAGAAATCAAAACATCAACTTTATTATAGTACATTGTAACTGGTAAACATTGAATGCATCATCAGAACACAGAATATTTTTGAAAGTTTACCGAGAGCAGTAATAATAAATTATGCTGGGCTGGACAGTATGGCATTGGGGAAAACTCAGAAGAGGGAAACCGTTGCTCAAGAAATATCAGAAAATGAAAATGTCACCGGGTACCATGGTGAACATTTTTTCCACAAGTTTTACTTACATACATTGCGAATTACTACGATCTACATATCACACCGTAAGGGGGTGTGCTCCGGCGGCCTTTCAGATGCTCGTCGATTGCTAACCATCAATACTTCAGTTGATGAATTCTCACGCAGTCGCCCAAACATACGCATAAGGCGTAGGCGATAAATCTTCAAAGTATTGAATATAATGTGGCACAGTGGGAATATAACTCACTCTCTGAGTCCAAATAGTGATCACTGGATTAATCATGATACCAACGATTAAAAGACGGAAAAAAAGGTTGGTTGCAGTTTTGTAATAATTGTTAATTTGACATGTTTCTCCACAAAAAATACTGAATAGGTACAAGAGCCGATACGGAAGACACGTGAAGAAAGTCCATAATGTGCTGGAAAACAAGAAGAACAGCCGACGAAACAGTTTCTGNNNNNNNNNCTATCGTTAAGAGACTTTGACTAAATTTTGAATACCGATCGTTGCCGCTCCTCCATATGGGTCAAATTGTGAGCAATGCAGTAGATCAAAGCTGATAAGGAAAATGACGTAAGAATCATTACGACATAGAATATGGGGCTCAAAAGATATACATAAGGATTAAGTGATACTCCAAGACAGCTTCCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCAAAATGTCATCTACATGGAACATTTTCTAAGTTGTATTTCAGAACTAACTAGTCAGCTCTTCATACCTAAGATACCTACATGTAAATATTGATTTCAATATTATTTCCGTGGGTCTTAAAAAAACTCCAATTCAGATTTGATCAGTATTTCGATTTGCAAAACTTTTATTAGAGGTTTTGATACTTGTGTAATACAGCGTATTTCATTTTCTTTTTTCCCGACTTCAATAGACATTTATAAAAAATCATCTCACCGCGCGTTCAGCATTTTTTTAAATAAAATGTTTTGGTATGAAAGGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCACAATACGCTATATAACTTAGAATGTTTTGTTTAAAAATGTATTGTTAACTTTTAATATGATGTTTTTTAATATGGTGTATAATATACAGGTACCATCTTCCTTTTTGAAACTTTCAGTTTACGTTAATGTTTTGGTTTTTTATCGTTCAAATTTATGACATTGCTGTATTTTGTTTCAATATCTAANNNNNNNNNNNNNCAAAACTCCATTCGTCGTGATCAAATGTTTTGTTTTGCAATAAAAATAACTTACTCGAGTTATTTTCAAAAAGGTGACAAGTGCGATGTTCATTGCATAAAGTCCTCCCCATGTCGCTGCAGTAATCCATAAAAGCCGTTTCCGATTCACAATTTGATAGTAATGCAACGGAAATTGAATGTAGATCAGCTTGTCAACATTCAACCTAAAATAGAAACTACTTTTTCATGACACCATTTTCCAAAAATCGTACCAAACGAGATTCAAGCAACTGCACATTTGACACGTCCAAATGATAACATAGTAGGGATGGCAAAGCCAAAGATTAAAATGTGAGAGCCATGGGCGAGTTTTCATGTACACAATACACATCAAAAGATCCGCCACTGTCATGTTGATAACAATTATCTGAAAACTGCTTTTGTAAAGATCGTTCTTAGCTCAAGATGTATGAATTTCGATCTATTTCTTTTTTAAAAGAGATTTCCTACCTGTCTAGGCTTATCTTCCGTATTGATATATGTGAGTGCAATCCATAGTACTAATGCGTTGAAAACTGTACCAACAATGCCACAACTGATATAAAACGCCGTTTCTCCTAATGTTAAGTTTTCTACAAATGGTTTTGTGACATTTGCAATAATGTCCGTTGAGTTCATTCTGAAATTTGTTTTGTTAGAAAAAAGGTCGAGATAAGTTCACGGCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCACAAAGAGTGTCAGAAACAGGACAGAGAACGATGAGGTGGAAGAATTAGATTACTCTGATAGGCTTGTTGAATTTTAAACCAGATCCTTCAAAGCACTTTTCCATTCAATGATAAAATGTGAACGTGACATCATTATGTCAATTGAAAAATATACATATGTGTATGCTCTCACGTAACTATTATGTCTTTTTGGNNNN",
				"GTAGGGATGGCAAAGCCAAAGATTAAAATGTGAGATTAAAGCTTTTACATGTACACAATACACATCAAAAGATCCGCCACTG"
				);
	}
	
	
	

}
